#pragma checksum "..\..\..\AdminSupplementsWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "1B79AEFB03C62B5F86525197C96BC07CA42B703D"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace KeepTrackAppUI {
    
    
    /// <summary>
    /// AdminSupplementsWindow
    /// </summary>
    public partial class AdminSupplementsWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 26 "..\..\..\AdminSupplementsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid SuppGrid;
        
        #line default
        #line hidden
        
        
        #line 52 "..\..\..\AdminSupplementsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox NameBox;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\..\AdminSupplementsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox DosageBox;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\..\AdminSupplementsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox InstructionsBox;
        
        #line default
        #line hidden
        
        
        #line 61 "..\..\..\AdminSupplementsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox BenefitsBox;
        
        #line default
        #line hidden
        
        
        #line 64 "..\..\..\AdminSupplementsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox RisksBox;
        
        #line default
        #line hidden
        
        
        #line 84 "..\..\..\AdminSupplementsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EditNameBox;
        
        #line default
        #line hidden
        
        
        #line 87 "..\..\..\AdminSupplementsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EditDosageBox;
        
        #line default
        #line hidden
        
        
        #line 90 "..\..\..\AdminSupplementsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EditInstructionsBox;
        
        #line default
        #line hidden
        
        
        #line 93 "..\..\..\AdminSupplementsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EditBenefitsBox;
        
        #line default
        #line hidden
        
        
        #line 96 "..\..\..\AdminSupplementsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EditRisksBox;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.8.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/KeepTrackAppUI;component/adminsupplementswindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\AdminSupplementsWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.8.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 13 "..\..\..\AdminSupplementsWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.GoToEditUsers_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            
            #line 14 "..\..\..\AdminSupplementsWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.GoToAdminRecipes_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            
            #line 15 "..\..\..\AdminSupplementsWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.GoToAdminSupplements_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            
            #line 16 "..\..\..\AdminSupplementsWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.GoToAdminProgress_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.SuppGrid = ((System.Windows.Controls.DataGrid)(target));
            
            #line 26 "..\..\..\AdminSupplementsWindow.xaml"
            this.SuppGrid.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.SuppGrid_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 6:
            this.NameBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.DosageBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.InstructionsBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            this.BenefitsBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.RisksBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 11:
            
            #line 67 "..\..\..\AdminSupplementsWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AddSupplement_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.EditNameBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 13:
            this.EditDosageBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 14:
            this.EditInstructionsBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 15:
            this.EditBenefitsBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 16:
            this.EditRisksBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 17:
            
            #line 100 "..\..\..\AdminSupplementsWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.UpdateSupplement_Click);
            
            #line default
            #line hidden
            return;
            case 18:
            
            #line 101 "..\..\..\AdminSupplementsWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.DeleteSupplement_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

