#pragma checksum "..\..\..\AdminRecipesWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "D43CCFAD0DCD34C33968C786C5012E3A80303A79"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace KeepTrackAppUI {
    
    
    /// <summary>
    /// AdminRecipesWindow
    /// </summary>
    public partial class AdminRecipesWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 26 "..\..\..\AdminRecipesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid RecipeGrid;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\..\AdminRecipesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox AddTitleBox;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\..\AdminRecipesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox AddCategoryBox;
        
        #line default
        #line hidden
        
        
        #line 61 "..\..\..\AdminRecipesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox AddIngredientsBox;
        
        #line default
        #line hidden
        
        
        #line 64 "..\..\..\AdminRecipesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox AddInstructionsBox;
        
        #line default
        #line hidden
        
        
        #line 67 "..\..\..\AdminRecipesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox AddImageBox;
        
        #line default
        #line hidden
        
        
        #line 72 "..\..\..\AdminRecipesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox AddCaloriesBox;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\..\AdminRecipesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox AddProteinBox;
        
        #line default
        #line hidden
        
        
        #line 80 "..\..\..\AdminRecipesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox AddCarbsBox;
        
        #line default
        #line hidden
        
        
        #line 84 "..\..\..\AdminRecipesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox AddFatBox;
        
        #line default
        #line hidden
        
        
        #line 109 "..\..\..\AdminRecipesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TitleBox;
        
        #line default
        #line hidden
        
        
        #line 112 "..\..\..\AdminRecipesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CategoryBox;
        
        #line default
        #line hidden
        
        
        #line 115 "..\..\..\AdminRecipesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox IngredientsBox;
        
        #line default
        #line hidden
        
        
        #line 118 "..\..\..\AdminRecipesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox InstructionsBox;
        
        #line default
        #line hidden
        
        
        #line 122 "..\..\..\AdminRecipesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CaloriesBox;
        
        #line default
        #line hidden
        
        
        #line 123 "..\..\..\AdminRecipesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ProteinBox;
        
        #line default
        #line hidden
        
        
        #line 124 "..\..\..\AdminRecipesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CarbsBox;
        
        #line default
        #line hidden
        
        
        #line 125 "..\..\..\AdminRecipesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox FatBox;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.8.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/KeepTrackAppUI;component/adminrecipeswindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\AdminRecipesWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.8.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 13 "..\..\..\AdminRecipesWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.GoToEditUsers_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            
            #line 14 "..\..\..\AdminRecipesWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.GoToAdminRecipes_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            
            #line 15 "..\..\..\AdminRecipesWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.GoToAdminSupplements_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            
            #line 16 "..\..\..\AdminRecipesWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.GoToAdminProgress_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.RecipeGrid = ((System.Windows.Controls.DataGrid)(target));
            
            #line 26 "..\..\..\AdminRecipesWindow.xaml"
            this.RecipeGrid.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.RecipeGrid_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 6:
            this.AddTitleBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.AddCategoryBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.AddIngredientsBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            this.AddInstructionsBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.AddImageBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 11:
            this.AddCaloriesBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 12:
            this.AddProteinBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 13:
            this.AddCarbsBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 14:
            this.AddFatBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 15:
            
            #line 89 "..\..\..\AdminRecipesWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AddRecipe_Click);
            
            #line default
            #line hidden
            return;
            case 16:
            this.TitleBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 17:
            this.CategoryBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 18:
            this.IngredientsBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 19:
            this.InstructionsBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 20:
            this.CaloriesBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 21:
            this.ProteinBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 22:
            this.CarbsBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 23:
            this.FatBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 24:
            
            #line 130 "..\..\..\AdminRecipesWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.UpdateRecipe_Click);
            
            #line default
            #line hidden
            return;
            case 25:
            
            #line 131 "..\..\..\AdminRecipesWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.DeleteRecipe_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

